name: mvde
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # or 12.1 depending on your setup
  - pip
  - pip:
    - transformers>=4.30.0
    - accelerate>=0.20.0
    - omegaconf>=2.3.0
    - hydra-core>=1.3.0
    - opencv-python>=4.8.0
    - pillow>=10.0.0
    - numpy>=1.24.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - tqdm>=4.65.0
    - wandb>=0.15.0
    - timm>=0.9.0
    - pydantic>=2.0.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - black>=23.0.0
    - isort>=5.12.0
    - ruff>=0.0.270
    - pre-commit>=3.3.0
    - jupyter>=1.0.0
    - ipywidgets>=8.0.0
    - datasets>=2.13.0
    - pycocotools>=2.0.6
    - -e .
