# Base configuration for MVDE experiments
# Default settings for inference and training

model:
  vila:
    model_name: "Efficient-Large-Model/VILA1.5-8b"
    device_map: "auto"
    torch_dtype: "float16"
    trust_remote_code: true
    
  ps3:
    num_look_close: 2
    num_token_look_close: 2048
    select_num_each_scale: "256+512"
    
  depth:
    estimator: "midas"  # "midas" or "zoe"
    model_type: "DPT_Large"  # for MiDaS
    device: "cuda"
    
  head:
    type: "mlp"  # "mlp" or "lora"
    hidden_dims: [512, 256, 128]
    output_dim: 1  # scalar distance
    dropout: 0.1
    activation: "relu"

data:
  image_size: [384, 384]
  normalize: true
  augment: false
  batch_size: 1
  
paths:
  data_root: "${oc.env:DATA_ROOT,./data}"
  cache_dir: "${oc.env:CACHE_DIR,./cache}"
  output_dir: "./runs"
  log_dir: "./runs/logs"

training:
  epochs: 10
  learning_rate: 1e-4
  weight_decay: 1e-5
  warmup_steps: 100
  gradient_clip: 1.0
  save_every: 2
  eval_every: 1
  
inference:
  max_tokens: 512
  temperature: 0.7
  top_p: 0.9
  do_sample: true

logging:
  level: "INFO"
  wandb:
    project: "${oc.env:WANDB_PROJECT,mvde-experiments}"
    entity: "${oc.env:WANDB_ENTITY,null}"
    tags: ["base", "vila", "depth"]

device:
  cuda_visible_devices: "${oc.env:CUDA_VISIBLE_DEVICES,0}"
  mixed_precision: true
